# API Limits and Defaults
MAX_RESULTS_LIMIT = 2500
DEFAULT_MAX_RESULTS = 100
DEFAULT_DAYS_AHEAD = 7

# Field Length Limits
MAX_SUMMARY_LENGTH = 1024
MAX_DESCRIPTION_LENGTH = 8192
MAX_LOCATION_LENGTH = 1024
MAX_QUERY_LENGTH = 500

# Event Status Options
EVENT_STATUS_CONFIRMED = "confirmed"
EVENT_STATUS_TENTATIVE = "tentative" 
EVENT_STATUS_CANCELLED = "cancelled"

VALID_EVENT_STATUSES = [
    EVENT_STATUS_CONFIRMED,
    EVENT_STATUS_TENTATIVE,
    EVENT_STATUS_CANCELLED
]

# Attendee Response Status Options
RESPONSE_NEEDS_ACTION = "needsAction"
RESPONSE_DECLINED = "declined"
RESPONSE_TENTATIVE = "tentative"
RESPONSE_ACCEPTED = "accepted"

VALID_RESPONSE_STATUSES = [
    RESPONSE_NEEDS_ACTION,
    RESPONSE_DECLINED,
    RESPONSE_TENTATIVE,
    RESPONSE_ACCEPTED
]

# Calendar Default Settings
DEFAULT_CALENDAR_ID = "primary"

# DateTime Formats
ISO_DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"
DATE_FORMAT = "%Y-%m-%d"